import type { Metadata } from "next";
import {  Oswald, Style_Script } from "next/font/google";
import "./globals.css";
import Providers from "./components/provider/providers";


const styleScript = Style_Script({
  variable: "--font-style-script",
  subsets: ["latin"],
  weight: "400"
})

const oswald = Oswald({
  variable: "--oswald",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "English Learning",
  description: "Generated by Huy Nguyen",
  icons: {
    icon: '/logo/EL_logo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${styleScript.variable} ${oswald.variable} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
